language: python
python:
  - "2.7"

install:
    - pip install fabric
    - pip install nose
    - pip install coverage
    - pip install responses

script:
    - nosetests -v --with-coverage --cover-package=fabric_digitalocean

after_success:
    - bash <(curl -s https://codecov.io/bash)
