language: python
python:
  - "2.7"

install:
    - pip install -e .[test]

script:
    - nosetests -v --with-coverage --cover-package=fabric_digitalocean

after_success:
    - bash <(curl -s https://codecov.io/bash)
